# Generated by Django 6.0.5 on 2026-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('prestado', 'Prestado'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], default='prestado', max_length=20),
        ),
    ]
