# Generated by Django 4.2.30 on 2026-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('retrasado', 'Retrasado')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
