# Generated by Django 4.2.30 on 2026-04-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('empleado', 'Empleado'), ('departamento', 'Departamento')], default='estudiante', max_length=30)),
            ],
        ),
    ]
