# Generated by Django 4.2.30 on 2026-04-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo_incidencia', models.CharField(choices=[('daño', 'Daño'), ('pérdida', 'Pérdida'), ('otro', 'Otro')], default='daño', max_length=30)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='prestamos.prestamo')),
            ],
        ),
    ]
